### ISSUE TITLE
ACNA-363 - Publish aio-cli v2.0.1 final release

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli#56]
- [x] Publish pre-release #47 
- [x] Get sign-off on release after testing period
- [x] npm publish [aio-cli](https://github.com/adobe/aio-cli) release from pre-release (patch version)
    - [x] publish new aio-cna-core-config module https://github.com/adobe/aio-cna-core-config/issues/6
    - [x] publish new aio-cli-plugin-config plugin https://github.com/adobe/aio-cli-plugin-config/issues/55
    - [x] publish new aio-cli-plugin-jwt-auth plugin https://github.com/adobe/aio-cli-plugin-jwt-auth/issues/46
    - [x] publish new aio-cli-plugin-console plugin https://github.com/adobe/aio-cli-plugin-console/issues/55
- [x] Post-publish: Make sure the v2.0 docs are integrated (sent PR https://github.com/AdobeDocs/adobeio-runtime/pull/38)
